services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: jami_dev
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=3003
      - NODE_ENV=test
    ports:
      - 3000:3003
    container_name: jami_dev

  db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: jami_db
